config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  get 'gems', to: 'welcome#gems'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'

  resources :news
  resources :gemposts

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gempost.rb
class Gempost < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gemposts_controller.rb
class GempostsController < ApplicationController
  before_action :authorize_admin, except: [:show]
  before_action :set_gempost, only: [:show, :edit, :update, :destroy]

  # GET /gemposts
  # GET /gemposts.json
  def index
    @gemposts = Gempost.all
  end

  # GET /gemposts/1
  # GET /gemposts/1.json
  def show
  end

  # GET /gemposts/new
  def new
    @gempost = Gempost.new
  end

  # GET /gemposts/1/edit
  def edit
  end

  # POST /gemposts
  # POST /gemposts.json
  def create
    @gempost = Gempost.new(gempost_params)

    respond_to do |format|
      if @gempost.save
        format.html { redirect_to @gempost, notice: 'Gempost was successfully created.' }
        format.json { render :show, status: :created, location: @gempost }
      else
        format.html { render :new }
        format.json { render json: @gempost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gemposts/1
  # PATCH/PUT /gemposts/1.json
  def update
    respond_to do |format|
      if @gempost.update(gempost_params)
        format.html { redirect_to @gempost, notice: 'Gempost was successfully updated.' }
        format.json { render :show, status: :ok, location: @gempost }
      else
        format.html { render :edit }
        format.json { render json: @gempost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gemposts/1
  # DELETE /gemposts/1.json
  def destroy
    @gempost.destroy
    respond_to do |format|
      format.html { redirect_to gemposts_url, notice: 'Gempost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gempost
      @gempost = Gempost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gempost_params
      params.require(:gempost).permit(:title, :content, :img)
    end

    def authorize_admin
      return unless !admin_signed_in?
      redirect_to root_path, alert: 'Admins only!'
    end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authorize_admin, except: [:show]
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content)
    end

    def authorize_admin
      return unless !admin_signed_in?
      redirect_to root_path, alert: 'Admins only!'
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @news = News.order("created_at desc").limit(3)
    @gemposts = Gempost.all.limit(1)
  end

  def gems
   @gemposts = Gempost.all
  end

  def about
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gemposts_helper.rb
module GempostsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gemposts/_form.html.erb
<%= form_with(model: gempost, local: true) do |form| %>
  <% if gempost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gempost.errors.count, "error") %> prohibited this gempost from being saved:</h2>

      <ul>
      <% gempost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gemposts/edit.html.erb
<h1>Editing Gempost</h1>

<%= render 'form', gempost: @gempost %>

<%= link_to 'Show', @gempost %> |
<%= link_to 'Back', gemposts_path %>

app/views/gemposts/index.html.erb
<h1>Gemposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gemposts.each do |gempost| %>
      <tr>
        <td><%= gempost.title %></td>
        <td><%= gempost.content %></td>
        <td><%= gempost.img %></td>
        <td><%= link_to 'Show', gempost %></td>
        <td><%= link_to 'Edit', edit_gempost_path(gempost) %></td>
        <td><%= link_to 'Destroy', gempost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gempost', new_gempost_path %>

app/views/gemposts/new.html.erb
<h1>New Gempost</h1>

<%= render 'form', gempost: @gempost %>

<%= link_to 'Back', gemposts_path %>

app/views/gemposts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @gempost.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gempost.content %>
</p>

<p>
  <strong>Img:</strong>
  <%= @gempost.img %>
</p>

<%= link_to 'Edit', edit_gempost_path(@gempost) %> |
<%= link_to 'Back', gemposts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gem's Shop | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500" rel="stylesheet">

  </head>

  <body>

    <%= render "welcome/header" %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

      <%= yield %>

    <%= render "welcome/footer" %>

  </body>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.content %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<% content_for :title, 'News' %>

<div class="container showNews">

  <h4 class="text-center"><%= @news.title %></h4>
  <p><%= @news.content %></p>



  <div class="text-center">
    <% if admin_signed_in? %>
      <%= button_to 'Edit', edit_news_path(@news), class: 'btn btn-mycolor', method: :get %>
    <% end %>
    <%= button_to 'Back', root_path, class: 'btn btn-mycolor', method: :get %>
  </div>

</div>

app/views/welcome/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted text-center">Made by K.P.</p>
  </div>

</footer>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to (fa_icon "gitlab", text: "GEM Shop"), root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item hvr-float">
        <%= active_link_to'Home', root_path, class: "nav-link", active: :exclusive %>
      </li>
      <li class="nav-item hvr-float">
        <%= active_link_to "Gem's", gems_path, class: "nav-link"  %>
      </li>
      <li class="nav-item hvr-float">
        <%= active_link_to "About", about_path, class: "nav-link"  %>
      </li>
      <li class="nav-item hvr-float">
        <%= active_link_to "Contact", contact_path, class: "nav-link"  %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if admin_signed_in? %>
          Admin Account
        <% else %>
          Account
        <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% if admin_signed_in? %>
          <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link dropdown-item'  %>
        <% else %>
          <%= link_to "Login", new_admin_session_path, :class => 'navbar-link dropdown-item'  %>
        <% end %>
      </div>
      </li>
    </ul>
  </div>
</nav>

app/views/welcome/about.html.erb
<% content_for :title, 'About' %>

app/views/welcome/contact.html.erb
<% content_for :title, 'Contact' %>

app/views/welcome/gems.html.erb
<% content_for :title, "Gem's List" %>

<div class="gemsHeader text-center">
  <h2>All Available Gem's</h2>
</div>


<div class="container" id="carouselCont">

  <div class=" owl-carousel owl-theme owl-loaded">

    <% @gemposts.each_with_index do |gems, index| %>

          <div class="item text-center">

            <%= image_tag gems.img %>
            <h5><%= gems.title %></h5>
            <p><%= gems.content %></p>

            <%= button_to '#', class: 'btn btn-mycolor'  do %>
              <%= fa_icon "shopping-cart", text: "Add To Cart" %>
            <% end %>

          </div>

      <% end %>

  </div>

  <div class="gemsBtn text-center">

  <% if admin_signed_in? %>

    <%= button_to "Add New Gem's",  new_gempost_path, class: 'btn btn-mycolor', method: :get %>

  <% end %>

  </div>


<!--
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
      <% @gemposts.each_with_index do |gems, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">

            <%= image_tag gems.img, class: 'd-block w-10' %>

          <div class="carousel-caption d-none d-md-block">

            <h5><%= gems.title %></h5>
            <p><%= gems.content %></p>

            <%= button_to '#', class: 'btn btn-mycolor'  do %>
              <%= fa_icon "shopping-cart", text: "Add To Cart" %>
            <% end %>

        </div>
      </div>
      <% end %>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
-->
</div>

app/views/welcome/index.html.erb
<% content_for :title, 'Home' %>

<div class="container headPage">
  <h2 class="text-center"><%= fa_icon "gitlab", text: "GEM Shop" %></h2>
  <p class="text-center">"Betcha You Don't Wan't Just One."</p>
</div>
<div class="container bodyPage">
  <div class="row">
    <div class="col-md-6">
      <div class="newsPage">
        <h4 class="text-center">Latest News</h4>

          <table>

            <% @news.each do |news| %>
              <tr>
                <td><h5><%= news.title %></h5></td>
              </tr>
              <tr>
                <td>
                  <div>
                    <% if news.content.length > 80 %>
                      <p><%= truncate(news.content, length: 80) %></p>
                      <%= link_to '...Read More', news_path(news.id), class: "readMore" %>
                      <br>
                    <% else %>
                      <%= news.content %>
                    <% end %>
                  <div>
                </td>
              </tr>
            <% end %>

          </table>

      </div>
    </div>
    <div class="col-md-6">
      <div class="latestItem">
        <h4 class="text-center">Latest Hot GEM!</h4>

        <table class="text-center">

            <% @gemposts.each do |gempost| %>
            <tr>
              <td><%= image_tag gempost.img, class: 'spinImage' %></td>
            </tr>
            <tr>
              <td><h5><%= gempost.title %></h5></td>
            </tr>
            <tr>
              <td><p><%= gempost.content %></p></td>
            </tr>
            <tr>
              <td><%= button_to "View More", gems_path, class: 'btn btn-mycolor', method: :get %>
            </tr>
            <% end %>

        </table>
      </div>
    </div>
  </div>
</div>